"""empty message

Revision ID: 0256244cd7c8
Revises: 3cd10cfce8c3
Create Date: 2019-06-28 11:19:50.401222

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0256244cd7c8'
down_revision = '3cd10cfce8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activation_code', sa.Column('expired', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activation_code', 'expired')
    # ### end Alembic commands ###
