"""empty message

Revision ID: 0a89c670fc7a
Revises: d68a2d971b70
Create Date: 2019-11-18 15:18:23.494405

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a89c670fc7a'
down_revision = 'd68a2d971b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deleted_alias_user_id_key', 'deleted_alias', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('deleted_alias_user_id_key', 'deleted_alias', ['user_id'])
    # ### end Alembic commands ###
