"""empty message

Revision ID: 10ad2dbaeccf
Revises: 696e17c13b8b
Create Date: 2019-12-30 18:16:40.110999

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ad2dbaeccf'
down_revision = 'a8b996f0be40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_domain', sa.Column('catch_all', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_domain', 'catch_all')
    # ### end Alembic commands ###
