"""empty message

Revision ID: 696e17c13b8b
Revises: e409f6214b2b
Create Date: 2019-12-29 10:43:29.169736

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696e17c13b8b'
down_revision = 'e409f6214b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_domain', sa.Column('spf_verified', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_domain', 'spf_verified')
    # ### end Alembic commands ###
