"""empty message

Revision ID: 01f808f15b2e
Revises: 10ad2dbaeccf
Create Date: 2019-12-30 18:47:17.726860

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f808f15b2e'
down_revision = '10ad2dbaeccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gen_email', sa.Column('automatic_creation', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gen_email', 'automatic_creation')
    # ### end Alembic commands ###
