"""empty message

Revision ID: a8b996f0be40
Revises: 696e17c13b8b
Create Date: 2019-12-30 00:22:25.114359

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b996f0be40'
down_revision = '696e17c13b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification')
    # ### end Alembic commands ###
