"""empty message

Revision ID: e409f6214b2b
Revises: d4e4488a0032
Create Date: 2019-12-29 10:29:44.979846

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e409f6214b2b'
down_revision = 'd4e4488a0032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alias_generator', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alias_generator')
    # ### end Alembic commands ###
