"""alias generator scheme

Revision ID: 8f53e718c79a
Revises: 9e1b06b9df13
Create Date: 2019-12-25 21:21:27.573197

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f53e718c79a'
down_revision = '9e1b06b9df13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alias_generator', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alias_generator')
    # ### end Alembic commands ###
