"""empty message

Revision ID: 4a7d35941602
Revises: 10a7947fda6b
Create Date: 2020-05-27 00:18:32.222689

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7d35941602'
down_revision = '10a7947fda6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paid_lifetime', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'paid_lifetime')
    # ### end Alembic commands ###
