"""empty message

Revision ID: 198c3aca9d8d
Revises: b0e9a389939a
Create Date: 2020-09-14 17:55:47.322585

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198c3aca9d8d'
down_revision = 'b0e9a389939a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('from_header', sa.Text(), nullable=True))
    op.add_column('contact', sa.Column('mail_from', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'mail_from')
    op.drop_column('contact', 'from_header')
    # ### end Alembic commands ###
