"""empty message

Revision ID: b77ab8c47cc7
Revises: 270d598c51e3
Create Date: 2020-07-23 11:08:34.913760

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77ab8c47cc7'
down_revision = '270d598c51e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_spam_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_spam_score')
    # ### end Alembic commands ###
