"""empty message

Revision ID: dbd80d290f04
Revises: f4b8232fa17e
Create Date: 2020-03-20 10:11:59.542933

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dbd80d290f04"
down_revision = "f4b8232fa17e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("contact", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("email_log", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("file", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("file", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("email_log", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("contact", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
