"""empty message

Revision ID: 95938a93ea14
Revises: 63fd3b240583
Create Date: 2020-08-16 11:50:11.765301

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95938a93ea14'
down_revision = '63fd3b240583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_log', sa.Column('spam_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_log', 'spam_score')
    # ### end Alembic commands ###
