"""empty message

Revision ID: 7c39ba4ec38d
Revises: ba6f13ccbabb
Create Date: 2020-01-30 10:10:01.245257

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c39ba4ec38d'
down_revision = 'ba6f13ccbabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_end', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_end')
    # ### end Alembic commands ###
