"""empty message

Revision ID: 54ca2dbf89c0
Revises: b17afc77ba83
Create Date: 2020-10-15 16:07:57.039554

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ca2dbf89c0'
down_revision = 'b17afc77ba83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_domain', sa.Column('premium_only', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_domain', 'premium_only')
    # ### end Alembic commands ###
