"""empty message

Revision ID: 57ef03f3ac34
Revises: bfd7b2302903
Create Date: 2020-04-13 20:49:01.061974

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ef03f3ac34'
down_revision = 'bfd7b2302903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_subscription', sa.Column('is_giveaway', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_subscription', 'is_giveaway')
    # ### end Alembic commands ###
