"""empty message

Revision ID: ea50319ea811
Revises: 95599239860a
Create Date: 2020-05-22 16:49:25.613344

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea50319ea811'
down_revision = '95599239860a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_otp', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_otp')
    # ### end Alembic commands ###
