"""empty message

Revision ID: bd05eac83f5f
Revises: dd911f880b75
Create Date: 2020-04-19 23:12:26.675833

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd05eac83f5f'
down_revision = 'dd911f880b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'apple_subscription', ['original_transaction_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apple_subscription', type_='unique')
    # ### end Alembic commands ###
