"""empty message

Revision ID: 903ec5f566e8
Revises: 3fa3a648c8e7
Create Date: 2020-02-23 14:11:46.332532

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903ec5f566e8'
down_revision = '3fa3a648c8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('new_email', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'mailbox', ['new_email'])
    op.add_column('users', sa.Column('full_mailbox', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_mailbox')
    op.drop_constraint(None, 'mailbox', type_='unique')
    op.drop_column('mailbox', 'new_email')
    # ### end Alembic commands ###
