"""empty message

Revision ID: b9f849432543
Revises: 9c976df9b9c4
Create Date: 2020-02-05 15:16:16.912369

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f849432543'
down_revision = '9c976df9b9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gen_email', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gen_email', 'note')
    # ### end Alembic commands ###
