"""empty message

Revision ID: d0f197979bd9
Revises: 84dec6c29c48
Create Date: 2020-11-07 12:47:44.131900

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f197979bd9'
down_revision = '84dec6c29c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('generic_subject', sa.String(length=78), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'generic_subject')
    # ### end Alembic commands ###
