"""empty message

Revision ID: 925b93d92809
Revises: 026e7a782ed6
Create Date: 2020-05-07 21:42:05.406865

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925b93d92809'
down_revision = '026e7a782ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_mailbox_user', 'mailbox', ['user_id', 'email'])
    op.drop_constraint('mailbox_email_key', 'mailbox', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('mailbox_email_key', 'mailbox', ['email'])
    op.drop_constraint('uq_mailbox_user', 'mailbox', type_='unique')
    # ### end Alembic commands ###
