"""empty message

Revision ID: 497cfd2a02e2
Revises: 92baf66b268b
Create Date: 2020-04-05 12:17:45.505741

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497cfd2a02e2'
down_revision = '92baf66b268b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('name', sa.String(length=512), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'name')
    # ### end Alembic commands ###
