"""empty message

Revision ID: ae94fe5c4e9f
Revises: de1b457472e0
Create Date: 2020-05-03 15:24:23.151311

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae94fe5c4e9f'
down_revision = 'de1b457472e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_domain', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_domain', 'name')
    # ### end Alembic commands ###
