"""empty message

Revision ID: ce15cf3467b4
Revises: 659d979b64ce
Create Date: 2020-05-17 19:38:30.255689

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce15cf3467b4'
down_revision = '659d979b64ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('replace_reverse_alias', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'replace_reverse_alias')
    # ### end Alembic commands ###
