"""empty message

Revision ID: 126c5af661b3
Revises: 026e7a782ed6
Create Date: 2020-05-08 23:01:13.644821

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126c5af661b3'
down_revision = '026e7a782ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('force_spf', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'force_spf')
    # ### end Alembic commands ###
