"""empty message

Revision ID: d1edb3cadec8
Revises: ac41029fb329
Create Date: 2020-11-24 11:14:24.208867

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1edb3cadec8'
down_revision = 'ac41029fb329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('disable_pgp', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'disable_pgp')
    # ### end Alembic commands ###
