"""empty message

Revision ID: 780a8344914b
Revises: c0d91ff18f77
Create Date: 2020-12-07 10:33:14.157476

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780a8344914b'
down_revision = 'c0d91ff18f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directory', sa.Column('disabled', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directory', 'disabled')
    # ### end Alembic commands ###
