"""empty message

Revision ID: abd093c85e01
Revises: 5cad8fa84386
Create Date: 2020-05-16 20:51:51.946998

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd093c85e01'
down_revision = '5cad8fa84386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias', sa.Column('disable_pgp', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alias', 'disable_pgp')
    # ### end Alembic commands ###
