"""empty message

Revision ID: 3c9542fc54e9
Revises: 6664d75ce3d4
Create Date: 2020-02-11 22:28:58.017384

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9542fc54e9'
down_revision = '6664d75ce3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_use_multiple_mailbox', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_use_multiple_mailbox')
    # ### end Alembic commands ###
