"""empty message

Revision ID: 9dc16e591f88
Revises: d0f197979bd9
Create Date: 2020-11-14 15:53:38.354575

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc16e591f88'
down_revision = 'd0f197979bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('invalid_email', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'invalid_email')
    # ### end Alembic commands ###
