"""empty message

Revision ID: eef0c404b531
Revises: 54ca2dbf89c0
Create Date: 2020-10-20 16:49:33.756896

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef0c404b531'
down_revision = '54ca2dbf89c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_domain', sa.Column('nb_failed_checks', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_domain', 'nb_failed_checks')
    # ### end Alembic commands ###
