"""empty message

Revision ID: b4146f7d5277
Revises: bd05eac83f5f
Create Date: 2020-04-26 10:26:18.625088

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4146f7d5277'
down_revision = 'bd05eac83f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alias', 'name')
    # ### end Alembic commands ###
