"""empty message

Revision ID: a5b4dc311a89
Revises: 749c2b85d20f
Create Date: 2020-06-07 00:08:08.588009

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b4dc311a89'
down_revision = '749c2b85d20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('pgp_finger_print', sa.String(length=512), nullable=True))
    op.add_column('contact', sa.Column('pgp_public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'pgp_public_key')
    op.drop_column('contact', 'pgp_finger_print')
    # ### end Alembic commands ###
