"""empty message

Revision ID: c0d91ff18f77
Revises: 56c790ec8ab4
Create Date: 2020-12-06 19:28:11.733022

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d91ff18f77'
down_revision = '56c790ec8ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('include_sender_in_reverse_alias', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'include_sender_in_reverse_alias')
    # ### end Alembic commands ###
