"""empty message

Revision ID: bdf76f4b65a2
Revises: 925b93d92809
Create Date: 2020-05-09 14:38:21.695415

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf76f4b65a2'
down_revision = '925b93d92809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('force_spf', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'force_spf')
    # ### end Alembic commands ###
