"""empty message

Revision ID: f580030d9beb
Revises: 903ec5f566e8
Create Date: 2020-02-23 16:03:46.064813

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f580030d9beb'
down_revision = '903ec5f566e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_mailbox_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'mailbox', ['default_mailbox_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_mailbox_id')
    # ### end Alembic commands ###
