"""empty message

Revision ID: bfd7b2302903
Revises: ea30c0b5b2e3
Create Date: 2020-04-13 13:21:14.857574

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd7b2302903'
down_revision = 'ea30c0b5b2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('intro_shown', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'intro_shown')
    # ### end Alembic commands ###
