"""empty message

Revision ID: 9081f1a90939
Revises: 11a35b448f83
Create Date: 2020-03-15 10:51:17.341046

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9081f1a90939'
down_revision = '11a35b448f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refused_email', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refused_email', 'deleted')
    # ### end Alembic commands ###
