"""empty message

Revision ID: 235355381f53
Revises: 7eef64ffb398
Create Date: 2020-03-05 21:37:42.266722

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235355381f53'
down_revision = '7eef64ffb398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gen_email', 'mailbox_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gen_email', 'mailbox_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
