"""empty message

Revision ID: a90e423c6763
Revises: 1abfc9e14d7e
Create Date: 2020-10-09 22:35:11.359186

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90e423c6763'
down_revision = '1abfc9e14d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_domain', sa.Column('random_prefix_generation', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_domain', 'random_prefix_generation')
    # ### end Alembic commands ###
