"""empty message

Revision ID: f5133dc851ee
Revises: 4912f3bd5ba2
Create Date: 2021-04-06 19:45:50.595838

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5133dc851ee'
down_revision = '4912f3bd5ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'published')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
