"""empty message

Revision ID: 78403c7b8089
Revises: c31a081eab74
Create Date: 2021-07-13 10:16:51.387510

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78403c7b8089'
down_revision = 'c31a081eab74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contact_reply_email'), 'contact', ['reply_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_reply_email'), table_name='contact')
    # ### end Alembic commands ###
