"""empty message

Revision ID: 2f1b3c759773
Revises: d750d578b068
Create Date: 2021-10-15 10:46:00.389295

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1b3c759773'
down_revision = 'd750d578b068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric2', sa.Column('nb_total_bounced_last_24h', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric2', 'nb_total_bounced_last_24h')
    # ### end Alembic commands ###
