"""empty message

Revision ID: 37feaba7c45d
Revises: 6204e57b4bc4
Create Date: 2021-11-01 18:40:32.932057

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37feaba7c45d'
down_revision = '6204e57b4bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_id_matching', sa.Column('email_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message_id_matching', 'email_log', ['email_log_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_id_matching', type_='foreignkey')
    op.drop_column('message_id_matching', 'email_log_id')
    # ### end Alembic commands ###
