"""empty message

Revision ID: a5eb5158c4d7
Revises: 68e2f38e33f4
Create Date: 2021-05-29 17:41:32.149720

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5eb5158c4d7'
down_revision = '68e2f38e33f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
