"""empty message

Revision ID: d1236c4dff71
Revises: e831a883153a
Create Date: 2021-03-06 17:43:53.727547

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1236c4dff71'
down_revision = 'e831a883153a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_log', sa.Column('auto_replied', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_log', 'auto_replied')
    # ### end Alembic commands ###
