"""empty message

Revision ID: 99d9e329b27f
Revises: 2f1b3c759773
Create Date: 2021-10-18 17:15:29.903802

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d9e329b27f'
down_revision = '2f1b3c759773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_id_matching',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('sl_message_id', sa.String(length=512), nullable=False),
    sa.Column('original_message_id', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_message_id'),
    sa.UniqueConstraint('sl_message_id')
    )
    op.add_column('email_log', sa.Column('message_id', sa.String(length=512), nullable=True))
    op.add_column('email_log', sa.Column('sl_message_id', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_log', 'sl_message_id')
    op.drop_column('email_log', 'message_id')
    op.drop_table('message_id_matching')
    # ### end Alembic commands ###
