"""empty message

Revision ID: bc75acacc98e
Revises: 7a105bfc0cd0
Create Date: 2021-09-21 11:15:15.573629

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc75acacc98e'
down_revision = '7a105bfc0cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactional_email_email_key', 'transactional_email', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('transactional_email_email_key', 'transactional_email', ['email'])
    # ### end Alembic commands ###
