"""empty message

Revision ID: 5ee767807344
Revises: b8b4f9598240
Create Date: 2021-09-27 12:19:14.398709

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee767807344'
down_revision = 'b8b4f9598240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'from_header')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('from_header', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
