"""empty message

Revision ID: d750d578b068
Revises: 2fbcad5527d7
Create Date: 2021-10-14 15:44:57.816738

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd750d578b068'
down_revision = '2fbcad5527d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounce', sa.Column('info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bounce', 'info')
    # ### end Alembic commands ###
