"""empty message

Revision ID: 4d3f91ddf3e9
Revises: 916a5257d18c
Create Date: 2021-09-10 18:12:21.374836

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3f91ddf3e9'
down_revision = '916a5257d18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ignore_loop_email', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ignore_loop_email')
    # ### end Alembic commands ###
