"""empty message

Revision ID: 8e70205a5308
Revises: 29ea13ed76f9
Create Date: 2021-06-27 17:49:55.836306

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e70205a5308'
down_revision = '29ea13ed76f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('random_alias_suffix', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'random_alias_suffix')
    # ### end Alembic commands ###
