"""empty message

Revision ID: 68e2f38e33f4
Revises: 6cc7f073b358
Create Date: 2021-05-25 18:13:07.614047

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e2f38e33f4'
down_revision = '6cc7f073b358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alias_hibp_hibp_id_fkey', 'alias_hibp', type_='foreignkey')
    op.drop_constraint('alias_hibp_alias_id_fkey', 'alias_hibp', type_='foreignkey')
    op.create_foreign_key(None, 'alias_hibp', 'alias', ['alias_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'alias_hibp', 'hibp', ['hibp_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alias_hibp', type_='foreignkey')
    op.drop_constraint(None, 'alias_hibp', type_='foreignkey')
    op.create_foreign_key('alias_hibp_alias_id_fkey', 'alias_hibp', 'alias', ['alias_id'], ['id'])
    op.create_foreign_key('alias_hibp_hibp_id_fkey', 'alias_hibp', 'hibp', ['hibp_id'], ['id'])
    # ### end Alembic commands ###
