"""empty message

Revision ID: 05e3af59929a
Revises: dfee471558bd
Create Date: 2021-07-29 08:50:42.388094

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e3af59929a'
down_revision = 'dfee471558bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hibp', sa.Column('date', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('hibp', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hibp', 'description')
    op.drop_column('hibp', 'date')
    # ### end Alembic commands ###
