"""empty message

Revision ID: d0ccd9d7ac0c
Revises: e7d7ebcea26c
Create Date: 2021-11-22 12:05:31.814178

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ccd9d7ac0c'
down_revision = 'e7d7ebcea26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fido', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fido', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fido', type_='foreignkey')
    op.drop_column('fido', 'user_id')
    # ### end Alembic commands ###
