"""empty message

Revision ID: 9014cca7097c
Revises: ffa75d04e6ef
Create Date: 2021-08-04 09:28:26.620053

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9014cca7097c'
down_revision = 'ffa75d04e6ef'
branch_labels = None
depends_on = None

from sqlalchemy.orm import sessionmaker

Session = sessionmaker()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute("""
    ALTER TABLE alias ADD COLUMN ts_vector tsvector GENERATED ALWAYS
    AS (to_tsvector('english', note)) STORED;
    """)

    op.create_index('ix_video___ts_vector__', 'alias', ['ts_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video___ts_vector__', table_name='alias')
    op.drop_column('alias', 'ts_vector')
    # ### end Alembic commands ###
