"""empty message

Revision ID: bbedc353f90c
Revises: d67eab226ecd
Create Date: 2021-10-26 12:05:38.840492

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbedc353f90c'
down_revision = 'd67eab226ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_referral_id_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'referral', ['referral_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_referral_id_fkey', 'client', 'referral', ['referral_id'], ['id'])
    # ### end Alembic commands ###
