"""empty message

Revision ID: 5662122eac21
Revises: 78403c7b8089
Create Date: 2021-07-22 10:16:12.468656

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5662122eac21'
down_revision = '78403c7b8089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expand_alias_info', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expand_alias_info')
    # ### end Alembic commands ###
