"""empty message

Revision ID: b8fd175c084a
Revises: 9031c9e28510
Create Date: 2021-11-18 10:29:13.512071

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fd175c084a'
down_revision = '9031c9e28510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('directory_quota', sa.Integer(), server_default='50', nullable=False))
    op.add_column('users', sa.Column('subdomain_quota', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subdomain_quota')
    op.drop_column('users', 'directory_quota')
    # ### end Alembic commands ###
