"""empty message

Revision ID: 6204e57b4bc4
Revises: 0b9150eb309d
Create Date: 2021-10-28 10:01:35.682267

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6204e57b4bc4'
down_revision = '0b9150eb309d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('block_forward', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'block_forward')
    # ### end Alembic commands ###
