"""empty message

Revision ID: 9d6adad83936
Revises: 94f14eb0fe5b
Create Date: 2021-03-23 10:23:17.879887

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6adad83936'
down_revision = '94f14eb0fe5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('date', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('nb_user', sa.Float(), nullable=True),
    sa.Column('nb_activated_user', sa.Float(), nullable=True),
    sa.Column('nb_premium', sa.Float(), nullable=True),
    sa.Column('nb_apple_premium', sa.Float(), nullable=True),
    sa.Column('nb_cancelled_premium', sa.Float(), nullable=True),
    sa.Column('nb_manual_premium', sa.Float(), nullable=True),
    sa.Column('nb_coinbase_premium', sa.Float(), nullable=True),
    sa.Column('nb_referred_user', sa.Float(), nullable=True),
    sa.Column('nb_referred_user_paid', sa.Float(), nullable=True),
    sa.Column('nb_alias', sa.Float(), nullable=True),
    sa.Column('nb_forward', sa.Float(), nullable=True),
    sa.Column('nb_block', sa.Float(), nullable=True),
    sa.Column('nb_reply', sa.Float(), nullable=True),
    sa.Column('nb_bounced', sa.Float(), nullable=True),
    sa.Column('nb_spam', sa.Float(), nullable=True),
    sa.Column('nb_verified_custom_domain', sa.Float(), nullable=True),
    sa.Column('nb_app', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric2')
    # ### end Alembic commands ###
