"""empty message

Revision ID: 4b483a762fed
Revises: d0ccd9d7ac0c
Create Date: 2021-11-26 18:09:58.148317

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b483a762fed'
down_revision = 'd0ccd9d7ac0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('expires_date', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'expires_date')
    # ### end Alembic commands ###
