"""empty message

Revision ID: a06066e3fbeb
Revises: 99d9e329b27f
Create Date: 2021-10-23 17:39:42.459541

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06066e3fbeb'
down_revision = '99d9e329b27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disable_automatic_alias_note', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disable_automatic_alias_note')
    # ### end Alembic commands ###
