"""empty message

Revision ID: 94f14eb0fe5b
Revises: d1236c4dff71
Create Date: 2021-03-06 18:10:10.450794

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f14eb0fe5b'
down_revision = 'd1236c4dff71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias', sa.Column('transfer_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'alias', ['transfer_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alias', type_='unique')
    op.drop_column('alias', 'transfer_token')
    # ### end Alembic commands ###
