"""empty message

Revision ID: 916a5257d18c
Revises: 424808e1fe49
Create Date: 2021-09-07 15:35:35.430202

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916a5257d18c'
down_revision = '424808e1fe49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('is_giveaway', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'is_giveaway')
    # ### end Alembic commands ###
