"""empty message

Revision ID: d8a3dfe674f2
Revises: ad467baf7ec8
Create Date: 2021-12-30 16:16:33.088147

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a3dfe674f2'
down_revision = 'ad467baf7ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apple_subscription', sa.Column('product_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apple_subscription', 'product_id')
    # ### end Alembic commands ###
