"""empty message

Revision ID: 424808e1fe49
Revises: d4392342465f
Create Date: 2021-08-20 12:11:57.901994

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424808e1fe49'
down_revision = 'd4392342465f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION pg_trgm')
    op.create_index('note_pg_trgm_index', 'alias', ['note'], unique=False, postgresql_ops={'note': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('note_pg_trgm_index', table_name='alias')
    op.execute('DROP EXTENSION pg_trgm')
    # ### end Alembic commands ###
