"""empty message

Revision ID: dd278f96ca83
Revises: fdb02bd105a8
Create Date: 2021-11-05 11:42:39.532067

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd278f96ca83'
down_revision = 'fdb02bd105a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_use_subdomain', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_use_subdomain')
    # ### end Alembic commands ###
