"""empty message

Revision ID: fdb02bd105a8
Revises: ff6c04869029
Create Date: 2021-11-05 10:29:36.925291

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb02bd105a8'
down_revision = 'ff6c04869029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_domain', sa.Column('is_sl_subdomain', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('public_domain', sa.Column('can_use_subdomain', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_domain', 'can_use_subdomain')
    op.drop_column('custom_domain', 'is_sl_subdomain')
    # ### end Alembic commands ###
