"""empty message

Revision ID: 4912f3bd5ba2
Revises: e11c3dd48a6f
Create Date: 2021-04-01 12:48:00.674978

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4912f3bd5ba2'
down_revision = 'e11c3dd48a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_user', 'nonce')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_user', sa.Column('nonce', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
