"""empty message

Revision ID: 517b79c56088
Revises: f398b261d9c6
Create Date: 2021-04-01 10:49:42.682281

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517b79c56088'
down_revision = 'f398b261d9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('approved', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('client', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'description')
    op.drop_column('client', 'approved')
    # ### end Alembic commands ###
