"""empty message

Revision ID: d8c55e79da54
Revises: 4d3f91ddf3e9
Create Date: 2021-09-17 16:30:23.299011

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c55e79da54'
down_revision = '4d3f91ddf3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_domain', sa.Column('auto_create_regex', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_domain', 'auto_create_regex')
    # ### end Alembic commands ###
