"""empty message

Revision ID: ff6c04869029
Revises: 37feaba7c45d
Create Date: 2021-11-02 15:25:51.898330

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6c04869029'
down_revision = '37feaba7c45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('one_click_unsubscribe_block_sender', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'one_click_unsubscribe_block_sender')
    # ### end Alembic commands ###
