"""empty message

Revision ID: 5047fcbd57c7
Revises: 9282e982bc05
Create Date: 2022-02-26 17:51:03.379676

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5047fcbd57c7'
down_revision = '9282e982bc05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alias_custom_domain_id'), 'alias', ['custom_domain_id'], unique=False)
    op.create_index(op.f('ix_alias_directory_id'), 'alias', ['directory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alias_directory_id'), table_name='alias')
    op.drop_index(op.f('ix_alias_custom_domain_id'), table_name='alias')
    # ### end Alembic commands ###
