"""add flags to user

Revision ID: 98040e190381
Revises: 0aaad1740797
Create Date: 2022-05-03 17:31:58.559032

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98040e190381'
down_revision = '0aaad1740797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flags', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flags')
    # ### end Alembic commands ###
