"""empty message

Revision ID: 516c21ea7d87
Revises: bfebc2d5c719
Create Date: 2022-07-02 18:10:05.689033

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516c21ea7d87'
down_revision = 'bfebc2d5c719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric2', sa.Column('nb_proton_premium', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric2', 'nb_proton_premium')
    # ### end Alembic commands ###
