"""add flags to the user model

Revision ID: 088f23324464
Revises: e866ad0e78e1
Create Date: 2022-05-12 13:32:30.898367

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088f23324464'
down_revision = 'e866ad0e78e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flags', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flags')
    # ### end Alembic commands ###
