"""empty message

Revision ID: bd7d032087b2
Revises: 516c21ea7d87
Create Date: 2022-07-02 18:28:41.643769

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7d032087b2'
down_revision = '516c21ea7d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric2', sa.Column('nb_proton_user', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric2', 'nb_proton_user')
    # ### end Alembic commands ###
