"""empty message

Revision ID: 4729b7096d12
Revises: 9282e982bc05
Create Date: 2022-02-25 12:11:10.991810

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4729b7096d12'
down_revision = '5047fcbd57c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('include_header_email_header', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'include_header_email_header')
    # ### end Alembic commands ###
