"""empty message

Revision ID: 74fe25b66e9b
Revises: 2c2093c82bc0
Create Date: 2022-11-30 18:21:44.235063

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fe25b66e9b'
down_revision = '2c2093c82bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_change', sa.Column('dirty_email', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('dirty_email', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dirty_email')
    op.drop_column('email_change', 'dirty_email')
    # ### end Alembic commands ###
