"""empty message

Revision ID: 673a074e4215
Revises: a7bcb872c12a
Create Date: 2022-06-22 17:17:24.383701

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673a074e4215'
down_revision = 'a7bcb872c12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_domain', sa.Column('hidden', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('public_domain', sa.Column('order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_domain', 'order')
    op.drop_column('public_domain', 'hidden')
    # ### end Alembic commands ###
