"""empty message

Revision ID: 753d2ed92d41
Revises: 3d05479d0d11
Create Date: 2022-01-04 14:54:37.818658

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753d2ed92d41'
down_revision = '3d05479d0d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_number', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_number', 'comment')
    # ### end Alembic commands ###
