"""empty message

Revision ID: fb3c1bf44c20
Revises: 07b870d7cc86
Create Date: 2022-01-25 21:35:11.187435

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3c1bf44c20'
down_revision = '07b870d7cc86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('automatic_alias_copy', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'automatic_alias_copy')
    # ### end Alembic commands ###
