"""add original_unsub behaviour config

Revision ID: d8d9348951ef
Revises: 088f23324464
Create Date: 2022-05-17 18:28:13.608810

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d9348951ef'
down_revision = '088f23324464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('original_unsub', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'original_unsub')
    # ### end Alembic commands ###
