"""Add unsubscribe behaviour

Revision ID: b0101a66bb77
Revises: bd7d032087b2
Create Date: 2022-07-06 19:52:04.324761

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0101a66bb77'
down_revision = 'bd7d032087b2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unsub_behaviour', sa.Integer(), default=0, server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unsub_behaviour')
    # ### end Alembic commands ###