"""empty message

Revision ID: 698424c429e9
Revises: 753d2ed92d41
Create Date: 2022-01-07 10:20:55.711691

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698424c429e9'
down_revision = '753d2ed92d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('automatic_created', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'automatic_created')
    # ### end Alembic commands ###
