"""empty message

Revision ID: 4bc54632d9aa
Revises: 46ecb648a47e
Create Date: 2023-11-07 14:02:17.610226

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc54632d9aa'
down_revision = '46ecb648a47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_newsletter_subject', table_name='newsletter')
    op.create_index(op.f('ix_newsletter_subject'), 'newsletter', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_subject'), table_name='newsletter')
    op.create_index('ix_newsletter_subject', 'newsletter', ['subject'], unique=True)
    # ### end Alembic commands ###
