"""empty message

Revision ID: f56ae0280018
Revises: 2c2093c82bc0
Create Date: 2023-03-24 17:35:35.166228

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56ae0280018'
down_revision = '2c2093c82bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_user', sa.Column('flags', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('public_domain', sa.Column('partner_id', sa.Integer(), nullable=True, sever_default='NULL'))
    op.create_foreign_key(None, 'public_domain', 'partner', ['partner_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'public_domain', type_='foreignkey')
    op.drop_column('public_domain', 'partner_id')
    op.drop_column('partner_user', 'flags')
    # ### end Alembic commands ###
