"""empty message

Revision ID: fb0ab73c1825
Revises: 4bc54632d9aa
Create Date: 2023-11-15 21:50:40.424160

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0ab73c1825'
down_revision = '4bc54632d9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('disable_smime', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('mailbox', sa.Column('smime_public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'smime_public_key')
    op.drop_column('mailbox', 'disable_smime')
    # ### end Alembic commands ###
