"""empty message

Revision ID: 418e4d2099a4
Revises: 2634b41f54db
Create Date: 2023-05-08 18:47:40.797307

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418e4d2099a4'
down_revision = '2634b41f54db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('validation_code', sa.String(length=128), nullable=True))
    op.add_column('mailbox', sa.Column('validation_expiration', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('mailbox', sa.Column('validation_tries', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'validation_tries')
    op.drop_column('mailbox', 'validation_expiration')
    op.drop_column('mailbox', 'validation_code')
    # ### end Alembic commands ###
