"""empty message

Revision ID: 52510a633d6f
Revises: 818b0a956205
Create Date: 2024-03-12 12:46:24.161644

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52510a633d6f"
down_revision = "818b0a956205"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alias", sa.Column("flags", sa.BigInteger(), server_default="0", nullable=False)
    )
    with op.get_context().autocommit_block():
        op.create_index(op.f("ix_alias_flags"), "alias", ["flags"], unique=False)
        op.create_index(op.f("ix_job_state"), "job", ["state"], unique=False)
        op.create_index(
            "ix_state_run_at_taken_at",
            "job",
            ["state", "run_at", "taken_at"],
            unique=False,
        )
        op.create_index(
            op.f("ix_notification_user_id"), "notification", ["user_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.drop_index(op.f("ix_notification_user_id"), table_name="notification")
        op.drop_index("ix_state_run_at_taken_at", table_name="job")
        op.drop_index(op.f("ix_job_state"), table_name="job")
        op.drop_index(op.f("ix_alias_flags"), table_name="alias")
    op.drop_column("alias", "flags")
    # ### end Alembic commands ###
