"""empty message

Revision ID: 135ea036e0e5
Revises: e38002759d8f
Create Date: 2025-05-30 18:45:22.717915

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135ea036e0e5'
down_revision = 'e38002759d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SMTP_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['alias_id'], ['alias.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SMTP_credentials_alias_id'), 'SMTP_credentials', ['alias_id'], unique=True)
    op.add_column('alias', sa.Column('enable_SMTP', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('email_log', sa.Column('is_SMTP', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('enable_SMTP_aliases', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enable_SMTP_aliases')
    op.drop_column('email_log', 'is_SMTP')
    op.drop_column('alias', 'enable_SMTP')
    op.drop_index(op.f('ix_SMTP_credentials_alias_id'), table_name='SMTP_credentials')
    op.drop_table('SMTP_credentials')
    # ### end Alembic commands ###
