"""empty message

Revision ID: 2b0ab9353b3c
Revises: 87da368d282b
Create Date: 2025-05-13 17:01:07.682728

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0ab9353b3c'
down_revision = '87da368d282b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abuser_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_bundle', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_abuser_data_id', 'abuser_data', ['id'], unique=False)
    op.create_table('abuser_lookup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('hashed_address', sa.String(), nullable=False),
    sa.Column('blob_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_k_bundle', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['abuser_data.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_abuser_lookup_hashed_address_blob_id', 'abuser_lookup', ['hashed_address', 'blob_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_abuser_lookup_hashed_address_blob_id', table_name='abuser_lookup')
    op.drop_table('abuser_lookup')
    op.drop_index('ix_abuser_data_id', table_name='abuser_data')
    op.drop_table('abuser_data')
    # ### end Alembic commands ###
