"""empty message

Revision ID: 4fac8c8a704c
Revises: 507afb2632cc
Create Date: 2019-08-17 22:16:40.628595

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fac8c8a704c'
down_revision = '507afb2632cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorization_code', sa.Column('expired', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False))
    op.add_column('oauth_token', sa.Column('expired', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_token', 'expired')
    op.drop_column('authorization_code', 'expired')
    # ### end Alembic commands ###
