"""empty message

Revision ID: 507afb2632cc
Revises: 1b7d161d1012
Create Date: 2019-08-11 11:58:33.954561

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507afb2632cc'
down_revision = '1b7d161d1012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorization_code', sa.Column('response_type', sa.String(length=128), nullable=True))
    op.add_column('oauth_token', sa.Column('response_type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_token', 'response_type')
    op.drop_column('authorization_code', 'response_type')
    # ### end Alembic commands ###
