"""empty message

Revision ID: 9e1b06b9df13
Revises: 18e934d58f55
Create Date: 2019-12-25 17:22:27.887481

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1b06b9df13'
down_revision = '18e934d58f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_domain', sa.Column('dkim_verified', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_domain', 'dkim_verified')
    # ### end Alembic commands ###
