"""empty message

Revision ID: b0ec969cb693
Revises: d4e4488a0032
Create Date: 2019-12-27 23:43:15.822463

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ec969cb693'
down_revision = 'd4e4488a0032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_domain', sa.Column('spf_verified', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_domain', 'spf_verified')
    # ### end Alembic commands ###
