"""empty message

Revision ID: d4e4488a0032
Revises: 9e1b06b9df13
Create Date: 2019-12-27 15:19:11.060497

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e4488a0032'
down_revision = '9e1b06b9df13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enable_otp', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_secret')
    op.drop_column('users', 'enable_otp')
    # ### end Alembic commands ###
