from .views import (
    index,
    pricing,
    setting,
    custom_alias,
    billing,
    alias_log,
    unsubscribe,
    api_key,
    custom_domain,
    alias_contact_manager,
    mfa_setup,
    mfa_cancel,
    domain_detail,
    lifetime_licence,
)
